# Generated by Django 5.2.13 on 2026-05-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_add_profile_fields_and_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, help_text='Emoji veya ikon sınıfı', max_length=50, verbose_name='İkon')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Etkinlik Adı')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', verbose_name='Kapak Görseli')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('location', models.CharField(max_length=250, verbose_name='Mekan')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat (₺)')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Kapasite')),
                ('tickets_sold', models.PositiveIntegerField(default=0, verbose_name='Satılan Bilet')),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('PUBLISHED', 'Yayında'), ('SOLD_OUT', 'Tükendi'), ('CANCELLED', 'İptal Edildi'), ('COMPLETED', 'Tamamlandı')], default='DRAFT', max_length=20, verbose_name='Durum')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan mı?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.category', verbose_name='Kategori')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.organizer', verbose_name='Organizatör')),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
