# Generated by Django 5.2.13 on 2026-05-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(default='CREDIT_CARD', max_length=50, verbose_name='Ödeme Yöntemi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('status', models.CharField(choices=[('PENDING', 'Bekliyor'), ('SUCCESS', 'Başarılı'), ('FAILED', 'Başarısız')], default='PENDING', max_length=20, verbose_name='Durum')),
                ('card_brand', models.CharField(max_length=20, verbose_name='Kart Markası')),
                ('card_last4', models.CharField(max_length=4, verbose_name='Son 4 Hane')),
                ('transaction_id', models.CharField(blank=True, max_length=36, verbose_name='İşlem ID')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='Başarısızlık Nedeni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
