# Generated by Django 5.2.13 on 2026-05-03 15:42

import apps.tickets.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(default=apps.tickets.models.generate_unique_ticket_code, max_length=16, unique=True, verbose_name='Bilet Kodu')),
                ('holder_name', models.CharField(max_length=150, verbose_name='Bilet Sahibi')),
                ('is_used', models.BooleanField(default=False, verbose_name='Kullanıldı mı?')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Kullanım Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event', verbose_name='Etkinlik')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Bilet',
                'verbose_name_plural': 'Biletler',
                'ordering': ['-created_at'],
            },
        ),
    ]
