# Generated by Django 5.2.13 on 2026-05-03 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Alıcı E-posta')),
                ('subject', models.CharField(max_length=255, verbose_name='Konu')),
                ('template_name', models.CharField(max_length=100, verbose_name='Şablon Adı')),
                ('status', models.CharField(choices=[('SENT', 'Gönderildi'), ('FAILED', 'Başarısız')], default='SENT', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Zamanı')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'E-posta Kaydı',
                'verbose_name_plural': 'E-posta Kayıtları',
                'ordering': ['-sent_at'],
            },
        ),
    ]
